name: Validate Materials

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run validation script
        run: |
          export PYTHONPATH=$(pwd)  # Adiciona o diretório raiz ao PYTHONPATH
          python curadoria_coletiva/validate_materials.py
